name: medespoir-pipeline
on:
  push:
    branches:
      - dev

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/Touchlink-Medespoir/Medespoir%20Egypte
            azure-pipeline-name: 'Load Modules and Check Build'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
